#QUESTION 1:TẠO VIEW CÓ CHỨA DANH SÁCH NHÂN VIÊN THUỘC PHÒNG BAN SALE
SELECT * FROM `ACCOUNT`
WHERE DEPARTMENTID = ( SELECT DEPARTMENTID FROM DEPARTMENT
						WHERE DEPARTMENTNAME ="SALE");
                        
#QUESTION 2: TẠO VIEW CÓ CHỨA THÔNG TIN CÁC ACCOUNT THAM GIA VÀO NHIỀU GROUP NHẤT 
SELECT * FROM `ACCOUNT`
WHERE ACCOUNTID IN ( SELECT ACCOUNTID FROM GROUPACCOUNT
					 GROUP BY ACCOUNTID
                     HAVING COUNT(*) = ( SELECT MAX(COUNTS.ACC_COUNT) FROM 
											(SELECT COUNT(*) AS ACC_COUNT FROM GROUPACCOUNT
													GROUP BY ACCOUNTID) AS COUNTS)
					);

#QUESTION 3:TẠO VIEW CÓ CHỨA CÂU HỎI CÓ NHỮNG CONTENT QUÁ DÀI (CONTENT QUÁ 300 TỪ ĐƯỢC COI LÀ QUÁ DÀI) 
#VÀ XÓA NÓ ĐI 
WITH CTE3 AS (
	SELECT QUESTIONID,
			CONTENT,
            CATEGORYID,
            TYPEID,
            CREATORID,
            CREATEDATE
	FROM QUESTION
    WHERE LENGTH(CONTENT) > 300)
DELETE FROM CTE3;

#QUESTION 4:TẠO VIEW CÓ CHỨA DANH SÁCH CÁC PHÒNG BAN CÓ NHIỀU NHÂN VIÊN NHẤT 
SELECT DEPT.DEPARTMENTID, DEPARTMENTNAME, COUNT(*) AS NUM_OF_EMPLOYEE
FROM DEPARTMENT AS DEPT 
JOIN `ACCOUNT` AS ACC
ON DEPT.DEPARTMENTID = ACC.DEPARTMENTID
GROUP BY ACC.DEPARTMENTID
HAVING NUM = (SELECT MAX(C) FROM 
					(SELECT COUNT(*) AS C 
                     FROM `ACCOUNT` AS ACC1 
                     GROUP BY ACC1.DEPARTMENTID) AS CS);

#QUESTION 5: TẠO VIEW CÓ CHỨA TẤT CÁC CÁC CÂU HỎI DO USER HỌ NGUYỄN TẠO 
WITH CTE5 AS (
	SELECT Q.QUESTIONID,
			Q.CONTENT,
            Q.CATEGORYID,
            Q.TYPEID,
            Q.CREATORID,
            Q.CREATEDATE,
            ACC.FULLNAME
	FROM QUESTION AS Q INNER JOIN `ACCOUNT` AS ACC
    ON Q.CREATORID = ACC.ACCOUNTID
    WHERE ACC.FULLNAME LIKE "NGUYEN%")
SELECT * FROM CTE5;