/*QUESTION 1*/
SELECT 
	NV.FULLNAME, 
    PB.DEPARTMENTID,
    PB.DEPARTMENTNAME
FROM `ACCOUNT` NV
LEFT JOIN DEPARTMENT PB ON 
	(NV.DEPARTMENTID = PB.DEPARTMENTID);

/*QUESTION 2*/
SELECT *
FROM `ACCOUNT`
WHERE CREATEDATE > "2010-12-20";

/*QUESTION 3*/
SELECT *
FROM `ACCOUNT` NV
INNER JOIN POSITION POS ON
	(NV.POSITIONID = POS.POSITIONID)
WHERE POS.POSITIONNAME = "DEV";

/*QUESTION 4*/
SELECT 
	LJ.DEPARTMENTID,
    LJ.DEPARTMENTNAME
FROM(
	SELECT DP.DEPARTMENTID, DP.DEPARTMENTNAME, NV.ACCOUNTID, COUNT(NV.ACCOUNTID) AS AMOUNT
    FROM `DEPARTMENT` DP
	INNER JOIN `ACCOUNT` NV ON 
		(DP.DEPARTMENTID = NV.DEPARTMENTID)
    GROUP BY DP.DEPARTMENTID, DP.DEPARTMENTNAME
	) LJ
WHERE LJ.AMOUNT >= 3;

/*QUESTION 5*/
SELECT Q.CONTENT
FROM QUESTION Q
INNER JOIN 
	(SELECT 
		LK.QUESTIONID
	FROM
		(SELECT LN.QUESTIONID, MAX(MYCOUNT) AS MAX, MYCOUNT
		FROM (
			SELECT EQ.QUESTIONID, COUNT(EQ.QUESTIONID) MYCOUNT
			FROM `EXAMQUESTION` EQ
			GROUP BY EQ.QUESTIONID) LN
		GROUP BY LN.QUESTIONID) LK
	WHERE LK.MAX = LK.MYCOUNT) LK1 
ON LK1.QUESTIONID = Q.QUESTIONID;

/*QUESTION 6*/
SELECT CQ.CATEGORYID, CQ.CATEGORYNAME, COUNT(Q.CATEGORYID)
FROM CATEGORYQUESTION CQ, QUESTION Q
WHERE CQ.CATEGORYID = Q.CATEGORYID
GROUP BY CQ.CATEGORYID;

/*QUESTION 7*/
SELECT Q.QUESTIONID, Q.CONTENT, COUNT(EQ.EXAMID) AS SO_LAN_XUAT_HIEN
FROM  QUESTION Q
LEFT JOIN EXAMQUESTION EQ 
ON  EQ.QUESTIONID = Q.QUESTIONID
GROUP BY Q.QUESTIONID, Q.CONTENT
ORDER BY Q.QUESTIONID;

/*QUESTION 8*/
SELECT Q.CONTENT
FROM QUESTION Q
INNER JOIN 
	(
    SELECT 
		LK.QUESTIONID
	FROM
		(
        SELECT 
			LN.QUESTIONID, 
            MAX(MYCOUNT) AS MAX, 
			MYCOUNT
		FROM (
			SELECT AWS.QUESTIONID, COUNT(AWS.QUESTIONID) MYCOUNT
			FROM `ANSWER` AWS
			GROUP BY AWS.QUESTIONID) LN
		GROUP BY LN.QUESTIONID
        ORDER BY MAX DESC LIMIT 1) LK
	WHERE LK.MYCOUNT = LK.MAX) LK1
ON LK1.QUESTIONID = Q.QUESTIONID;

/*QUESTION 9*/
SELECT GR.GROUPID, GR.GROUPNAME, COUNT(GRAC.GROUPID) AS SO_ACCOUNT
FROM  `GROUP` GR
LEFT JOIN GROUPACCOUNT GRAC 
ON  GR.GROUPID = GRAC.GROUPID
GROUP BY GR.GROUPID, GR.GROUPNAME
ORDER BY GR.GROUPID;

/*QUESTION 10*/
SELECT POS.POSITIONNAME
FROM `POSITION` POS
INNER JOIN 
	(
    SELECT 
		LK.POSITIONID
	FROM
		(
        SELECT 
			LN.POSITIONID, 
            MIN(MYCOUNT) AS MIN, 
			MYCOUNT
		FROM (
			SELECT AC.POSITIONID, COUNT(AC.POSITIONID) MYCOUNT
			FROM `ACCOUNT` AC
			GROUP BY AC.POSITIONID) LN
		GROUP BY LN.POSITIONID
        ORDER BY MIN ASC LIMIT 1) LK
	WHERE LK.MYCOUNT = LK.MIN) LK1
ON LK1.POSITIONID = POS.POSITIONID;

/*QUESTION 11*/
SELECT
	DEPT.DEPARTMENTID,
    DEPT.DEPARTMENTNAME,
    COALESCE(DEV.DEV_COUNT, 0) DEV_COUNT,
	COALESCE(TEST.TEST_COUNT,0) TEST_COUNT,
    COALESCE(PM.PM_COUNT,0) PM_COUNT,
    COALESCE(BA.BA_COUNT,0) BA_COUNT,
    COALESCE(HR.HR_COUNT,0) HR_COUNT
FROM `DEPARTMENT` DEPT
LEFT JOIN `ACCOUNT` AC ON AC.DEPARTMENTID = DEPT.DEPARTMENTID
LEFT JOIN `POSITION` POS ON POS.POSITIONID = AC.POSITIONID
LEFT JOIN(
	SELECT
		COUNT(*) DEV_COUNT,
        AC.DEPARTMENTID
	FROM `ACCOUNT` AC 
    WHERE AC.POSITIONID = 1
    GROUP BY AC.DEPARTMENTID
    ) DEV ON DEPT.DEPARTMENTID = DEV.DEPARTMENTID
    
LEFT JOIN(
	SELECT
		COUNT(*) TEST_COUNT,
        AC.DEPARTMENTID
	FROM `ACCOUNT` AC   
    WHERE AC.POSITIONID = 2
    GROUP BY AC.DEPARTMENTID
    ) TEST ON DEPT.DEPARTMENTID = TEST.DEPARTMENTID
    
LEFT JOIN(
	SELECT
		COUNT(*) PM_COUNT,
        AC.DEPARTMENTID
	FROM `ACCOUNT` AC 
      WHERE AC.POSITIONID = 3
    GROUP BY AC.DEPARTMENTID
    ) PM ON DEPT.DEPARTMENTID = PM.DEPARTMENTID

LEFT JOIN(
	SELECT
		COUNT(*) BA_COUNT,
        AC.DEPARTMENTID
	FROM `ACCOUNT` AC 
	WHERE AC.POSITIONID = 4
    GROUP BY AC.DEPARTMENTID
    ) BA ON DEPT.DEPARTMENTID = BA.DEPARTMENTID
    
LEFT JOIN(
	SELECT
		COUNT(*) HR_COUNT,
        AC.DEPARTMENTID
	FROM `ACCOUNT` AC 
	WHERE AC.POSITIONID = 5
    GROUP BY AC.DEPARTMENTID
    ) HR ON DEPT.DEPARTMENTID = HR.DEPARTMENTID
GROUP BY DEPT.DEPARTMENTID;	

/*QUESTION 12*/
SELECT
	Q.QUESTIONID,
    Q.CONTENT,
    CQ.CATEGORYNAME,
    TQS.TYPENAME,
    AC.FULLNAME,
    Q.CREATEDATE
FROM `QUESTION` Q
LEFT JOIN `ANSWER` ASW ON Q.QUESTIONID = ASW.QUESTIONID
LEFT JOIN `TYPEQUESTION` TQS ON Q.TYPEID = TQS.TYPEID
LEFT JOIN `ACCOUNT` AC ON Q.CREATORID = AC.ACCOUNTID
LEFT JOIN `CATEGORYQUESTION` CQ ON Q.CATEGORYID = CQ.CATEGORYID
GROUP BY Q.QUESTIONID, Q.CONTENT;

/*QUESTION 13*/
SELECT
    TQS.TYPEID,
    TQS.TYPENAME,
    COALESCE(TN.SL, 0) SO_LUONG
FROM `TYPEQUESTION` TQS 
LEFT JOIN `QUESTION` Q  ON Q.TYPEID = TQS.TYPEID
LEFT JOIN(
	SELECT
		COUNT(*) SL,
        Q1.TYPEID
	FROM `QUESTION` Q1 
    LEFT JOIN `TYPEQUESTION` TQS1
    ON Q1.TYPEID  = TQS1.TYPEID
	WHERE  TQS1.TYPENAME LIKE '%TRẮC NGHIỆM%'
    GROUP BY Q1.TYPEID
    ) TN 
ON TN.TYPEID = TQS.TYPEID

GROUP BY TQS.TYPEID, TQS.TYPENAME;

/*QUESTION 14*/
SELECT GR.GROUPID, GR.GROUPNAME
FROM `GROUP` GR
WHERE GR.GROUPID NOT IN  
(
	SELECT GRAC.GROUPID
    FROM `GROUP` GR1, `GROUPACCOUNT` GRAC
    WHERE GR1.GROUPID = GRAC.GROUPID
);


/*QUESTION 15*/
SELECT GR.GROUPID, GR.GROUPNAME
FROM `GROUP` GR
WHERE GR.GROUPID NOT IN  
(
	SELECT GRAC.GROUPID
    FROM `GROUP` GR1, `GROUPACCOUNT` GRAC
    WHERE GR1.GROUPID = GRAC.GROUPID
);

/*QUESTION 16*/
SELECT Q.QUESTIONID, Q.CONTENT
FROM `QUESTION` Q
WHERE Q.QUESTIONID NOT IN  
(
	SELECT Q.QUESTIONID
    FROM `QUESTION` Q, `ANSWER` ASW
    WHERE Q.QUESTIONID = ASW.QUESTIONID
);

/*QUESTION 17*/
/*QUESTION 18*/
/*CÓ MẤY CÂU EM LÀM VẪN CHƯA QUEN NÊN CHƯA TỐI ƯU ĐƯỢC*/



