CREATE TABLE `DEPARTMENT`(
	`DEPARTMENTID` INT NOT NULL AUTO_INCREMENT,
	`DEPARTMENTNAME` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`DEPARTMENTID`)
    );
CREATE TABLE `POSITION`(
	`POSITIONID` INT NOT NULL AUTO_INCREMENT,
	`POSITIONNAME` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`POSITIONID`)
    );
CREATE TABLE `ACCOUNT`(
	`ACCOUNTID` INT NOT NULL AUTO_INCREMENT,
	`EMAIL` VARCHAR(50) NOT NULL,
    `USERNAME` VARCHAR(50) NOT NULL,
    `FULLNAME` VARCHAR(50) NOT NULL,
    `DEPARTMENTID` INT NOT NULL,
    `POSITIONID` INT NOT NULL,
    `CREATEDATE` DATE NOT NULL,
    PRIMARY KEY (`ACCOUNTID`)
    );
CREATE TABLE `GROUP`(
	`GROUPID` INT NOT NULL AUTO_INCREMENT,
	`GROUPNAME` VARCHAR(50) NOT NULL,
    `CREATORID` INT NOT NULL,
    `CREATEDATE` DATE NOT NULL, 
    PRIMARY KEY (`GROUPID`)
    );
CREATE TABLE `GROUPACCOUNT`(
	`GROUPID` INT NOT NULL,
	`JOINDATE` DATE NOT NULL,
    `ACCOUNTID` INT NOT NULL,
    CONSTRAINT `GAUNIQUE` UNIQUE (`GROUPID` ,`ACCOUNTID`)
);
CREATE TABLE `TYPEQUESTION`(
	`TYPEID` INT NOT NULL AUTO_INCREMENT,
	`TYPENAME` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`TYPEID`)
    );
CREATE TABLE `CATEGORYQUESTION`(
	`CATEGORYID` INT NOT NULL AUTO_INCREMENT,
	`CATEGORYNAME` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`CATEGORYID`)
    );
CREATE TABLE `QUESTION`(
	`QUESTIONID` INT NOT NULL AUTO_INCREMENT,
	`CONTENT` VARCHAR(25) NOT NULL,
    `CATEGORYID` INT NOT NULL,
	`TYPEID` INT NOT NULL,
    `CREATORID` INT NOT NULL,
    `CREATEDATE` DATE NOT NULL,
    PRIMARY KEY (`QUESTIONID`)
    );
CREATE TABLE `ANSWER`(
	`ANSWERID` INT NOT NULL AUTO_INCREMENT,
	`CONTENT` VARCHAR(50) NOT NULL,
    `QUESTIONID` INT NOT NULL,
    `ISCORRECT` BOOLEAN NOT NULL,
    PRIMARY KEY (`ANSWERID`)
);
CREATE TABLE `EXAM`(
	`EXAMID` INT NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(15) NOT NULL,
    `TITLE` VARCHAR(50) NOT NULL,
    `DURATION` DOUBLE NOT NULL,
    `CATEGORYID` INT NOT NULL,
    `CREATORID` INT NOT NULL,
    `CREATEDATE` DATE NOT NULL,
    PRIMARY KEY (`EXAMID`)
    );
CREATE TABLE `EXAMQUESTION`(
	`EXAMID` INT NOT NULL,
    `QUESTIONID` INT NOT NULL,
    CONSTRAINT `EQUNIQUE` UNIQUE (`EXAMID` ,`QUESTIONID`)
);
ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_ACCOUNT1` FOREIGN KEY (DEPARTMENTID) REFERENCES `DEPARTMENT`(DEPARTMENTID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_ACCOUNT2` FOREIGN KEY (POSITIONID) REFERENCES `POSITION`(POSITIONID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `GROUP` ADD CONSTRAINT `FK_GROUP` FOREIGN KEY (CREATORID) REFERENCES `ACCOUNT`(ACCOUNTID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `GROUPACCOUNT` ADD CONSTRAINT `FK_GROUPACCOUNT1` FOREIGN KEY (GROUPID) REFERENCES `GROUP`(GROUPID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `GROUPACCOUNT` ADD CONSTRAINT `FK_GROUPACCOUNT2` FOREIGN KEY (ACCOUNTID) REFERENCES `ACCOUNT`(ACCOUNTID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `QUESTION` ADD CONSTRAINT `FK_QUESTION1` FOREIGN KEY (CATEGORYID) REFERENCES `CATEGORYQUESTION`(CATEGORYID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `QUESTION` ADD CONSTRAINT `FK_QUESTION2` FOREIGN KEY (TYPEID) REFERENCES `TYPEQUESTION`(TYPEID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `QUESTION` ADD CONSTRAINT `FK_QUESTION3` FOREIGN KEY (CREATORID) REFERENCES `ACCOUNT`(ACCOUNTID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ANSWER` ADD CONSTRAINT `FK_ANSWER` FOREIGN KEY (QUESTIONID) REFERENCES `QUESTION`(QUESTIONID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `EXAM` ADD CONSTRAINT `FK_EXAM1` FOREIGN KEY (CATEGORYID) REFERENCES `CATEGORYQUESTION`(CATEGORYID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `EXAM` ADD CONSTRAINT `FK_EXAM2` FOREIGN KEY (CREATORID) REFERENCES `ACCOUNT`(ACCOUNTID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `EXAMQUESTION` ADD CONSTRAINT `FK_EXAMQUESTION1` FOREIGN KEY (EXAMID) REFERENCES `EXAM`(EXAMID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `EXAMQUESTION` ADD CONSTRAINT `FK_EXAMQUESTION2` FOREIGN KEY (QUESTIONID) REFERENCES `QUESTION`(QUESTIONID) ON DELETE CASCADE ON UPDATE CASCADE;

/*QUESTION 1*/
INSERT INTO DEPARTMENT(DEPARTMENTNAME) VALUES("SALE");
INSERT INTO DEPARTMENT(DEPARTMENTNAME) VALUES("MARKETING");
INSERT INTO DEPARTMENT(DEPARTMENTNAME) VALUES("ACCOUNTING");
INSERT INTO DEPARTMENT(DEPARTMENTNAME) VALUES("HUMAN RESOURCES");
INSERT INTO DEPARTMENT(DEPARTMENTNAME) VALUES("ADMINISTRATION");
INSERT INTO `POSITION`(POSITIONNAME) VALUES("DEV");
INSERT INTO `POSITION`(POSITIONNAME) VALUES("TEST");
INSERT INTO `POSITION`(POSITIONNAME) VALUES("PM");
INSERT INTO `POSITION`(POSITIONNAME) VALUES("BA");
INSERT INTO `POSITION`(POSITIONNAME) VALUES("HR");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC1@GMAIL.COM", "AC1","A C VAN 1",5,3,"2021-07-13");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC2@GMAIL.COM", "AC2","A C VAN 12",4,2,"2021-07-14");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC3@GMAIL.COM", "AC3","A C VAN 123",3,1,"2021-07-15");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC4@GMAIL.COM", "AC4","A C VAN 1234",2,5,"2021-07-16");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC5@GMAIL.COM", "AC5","A C VAN 12345",1,4,"2021-07-17");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC6@GMAIL.COM", "AC6","D C VAN 123456 O",2,3,"2021-07-18");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC7@GMAIL.COM", "AC7","A C VAN 123DAIHON",3,5,"2021-07-19");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC8@GMAIL.COM", "AC8","A C VAN 8",3,3,"2021-07-13");
INSERT INTO `ACCOUNT`(EMAIL,USERNAME,FULLNAME,DEPARTMENTID,POSITIONID,CREATEDATE) VALUES("AC9@GMAIL.COM", "AC9","A C VAN 9",4,3,"2021-07-13");
INSERT INTO `GROUP`(GROUPNAME,CREATORID,CREATEDATE) VALUES("GR1", 4,"2021-08-24");
INSERT INTO `GROUP`(GROUPNAME,CREATORID,CREATEDATE) VALUES("GR2", 1,"2018-08-25");
INSERT INTO `GROUP`(GROUPNAME,CREATORID,CREATEDATE) VALUES("GR3", 2,"2021-08-23");
INSERT INTO `GROUP`(GROUPNAME,CREATORID,CREATEDATE) VALUES("GR4", 5,"2021-08-26");
INSERT INTO `GROUP`(GROUPNAME,CREATORID,CREATEDATE) VALUES("GR5", 3,"2021-07-27");
INSERT INTO `GROUP`(GROUPNAME,CREATORID,CREATEDATE) VALUES("GR6", 4,"2021-08-24");
INSERT INTO GROUPACCOUNT(GROUPID,ACCOUNTID,JOINDATE) VALUES(5, 3,"2021-09-04");
INSERT INTO GROUPACCOUNT(GROUPID,ACCOUNTID,JOINDATE) VALUES(3, 2,"2021-09-05");
INSERT INTO GROUPACCOUNT(GROUPID,ACCOUNTID,JOINDATE) VALUES(1, 1,"2021-09-06");
INSERT INTO GROUPACCOUNT(GROUPID,ACCOUNTID,JOINDATE) VALUES(4, 4,"2021-09-07");
INSERT INTO GROUPACCOUNT(GROUPID,ACCOUNTID,JOINDATE) VALUES(2, 5,"2021-09-08");
INSERT INTO TYPEQUESTION(TYPENAME) VALUES("TRẮC NGHIỆM TÔ");
INSERT INTO TYPEQUESTION(TYPENAME) VALUES("TRẮC NGHIỆM KHOANH");
INSERT INTO TYPEQUESTION(TYPENAME) VALUES("TRẮC NGHIỆM ĐIỀN");
INSERT INTO TYPEQUESTION(TYPENAME) VALUES("TỰ LUẬN");
INSERT INTO TYPEQUESTION(TYPENAME) VALUES("TRẮC NGHIỆM GIẢI THÍCH");
INSERT INTO CATEGORYQUESTION(CATEGORYNAME) VALUES("JAVA");
INSERT INTO CATEGORYQUESTION(CATEGORYNAME) VALUES("DOTNET");
INSERT INTO CATEGORYQUESTION(CATEGORYNAME) VALUES("SQL");
INSERT INTO CATEGORYQUESTION(CATEGORYNAME) VALUES("PHP");
INSERT INTO CATEGORYQUESTION(CATEGORYNAME) VALUES("HTML/CSS");
INSERT INTO QUESTION(CONTENT,CATEGORYID,TYPEID,CREATORID,CREATEDATE) VALUES("CONTENT 1", 3, 5, 3,"2021-06-20");
INSERT INTO QUESTION(CONTENT,CATEGORYID,TYPEID,CREATORID,CREATEDATE) VALUES("CÂU HỎI CONTENT 2", 2, 4, 1,"2021-06-22");
INSERT INTO QUESTION(CONTENT,CATEGORYID,TYPEID,CREATORID,CREATEDATE) VALUES("CONTENT 3", 1, 3, 3,"2021-06-24");
INSERT INTO QUESTION(CONTENT,CATEGORYID,TYPEID,CREATORID,CREATEDATE) VALUES("CONTENT 4", 5, 2, 4,"2021-06-26");
INSERT INTO QUESTION(CONTENT,CATEGORYID,TYPEID,CREATORID,CREATEDATE) VALUES("CONTENT 5", 4, 1, 2,"2021-06-28");
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A1", 3, TRUE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A11", 3, FALSE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A12", 3, FALSE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A13", 3, TRUE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A2", 4, FALSE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A3", 5, FALSE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A4", 1, TRUE);
INSERT INTO ANSWER(CONTENT,QUESTIONID,ISCORRECT) VALUES("CONTENT A5", 2, TRUE);
INSERT INTO EXAM(`CODE`,TITLE,CATEGORYID,DURATION,CREATORID,CREATEDATE) VALUES("MD01", "KIỂM TRA 1", 2, 90, 3,"2019-09-01");
INSERT INTO EXAM(`CODE`,TITLE,CATEGORYID,DURATION,CREATORID,CREATEDATE) VALUES("MD02", "KIỂM TRA 2", 3, 60, 4,"2019-09-03");
INSERT INTO EXAM(`CODE`,TITLE,CATEGORYID,DURATION,CREATORID,CREATEDATE) VALUES("MD03", "KIỂM TRA 3", 4, 50, 5,"2021-09-04");
INSERT INTO EXAM(`CODE`,TITLE,CATEGORYID,DURATION,CREATORID,CREATEDATE) VALUES("MD04", "KIỂM TRA 4", 5, 30, 1,"2019-09-20");
INSERT INTO EXAM(`CODE`,TITLE,CATEGORYID,DURATION,CREATORID,CREATEDATE) VALUES("MD05", "KIỂM TRA 5", 1, 90, 2,"2021-09-06");
INSERT INTO EXAMQUESTION(EXAMID,QUESTIONID) VALUES(1, 3);
INSERT INTO EXAMQUESTION(EXAMID,QUESTIONID) VALUES(3, 5);
INSERT INTO EXAMQUESTION(EXAMID,QUESTIONID) VALUES(2, 4);
INSERT INTO EXAMQUESTION(EXAMID,QUESTIONID) VALUES(5, 1);
INSERT INTO EXAMQUESTION(EXAMID,QUESTIONID) VALUES(4, 2);

/*QUESTION 2*/
SELECT *
FROM DEPARTMENT;

/*QUESTION 3*/
SELECT DEPARTMENTID
FROM DEPARTMENT 
WHERE DEPARTMENTNAME = "SALE";

/*QUESTION 4*/
SELECT * 
FROM  `ACCOUNT` 
ORDER BY LENGTH(FULLNAME) DESC ;

/*QUESTION 5*/
SELECT * 
FROM  `ACCOUNT`
WHERE `ACCOUNT`.DEPARTMENTID = 3
ORDER BY LENGTH(FULLNAME) DESC LIMIT 1;

/*QUESTION 6*/
SELECT GROUPNAME
FROM `GROUP`
WHERE CREATEDATE < "2019-12-20";

/*QUESTION 7*/
SELECT QUESTIONID 
FROM `ANSWER`
GROUP BY QUESTIONID
HAVING COUNT(QUESTIONID) >= 4;

/*QUESTION 8*/
SELECT `CODE`
FROM `EXAM`
WHERE CREATEDATE < "2019-12-20" AND DURATION >= 60;

/*QUESTION 9*/
SELECT * 
FROM  `GROUP` 
ORDER BY CREATEDATE DESC LIMIT 5;

/*QUESTION 10*/
SELECT COUNT(ACCOUNTID) AS "TONG SO NHAN VIEN CUA PHONG BAN CO ID =2"
FROM `ACCOUNT`
WHERE `ACCOUNT`.DEPARTMENTID = 2;

/*QUESTION 11*/
SELECT *
FROM `ACCOUNT`
WHERE FULLNAME LIKE 'D%O';

/*QUESTION 12*/
DELETE 
FROM EXAM 
WHERE CREATEDATE < "2019-12-20";


/*QUESTION 13*/
DELETE 
FROM QUESTION 
WHERE CONTENT LIKE 'CÂU HỎI%';

/*QUESTION 14*/
UPDATE `ACCOUNT`
SET FULLNAME = 'NGUYỄN BÁ LỘC' , EMAIL ='LOC.NGUYENBA@VTI.COM.VN'
WHERE ACCOUNTID = 5;

/*QUESTION 15*/
UPDATE `GROUPACCOUNT`
SET GROUPID = 4 
WHERE ACCOUNTID = 5;