/*QUESTION 1*/
CREATE VIEW LIST_EMPLOYEE_OF_SALE AS
SELECT *
FROM(
	SELECT 
		NV.ACCOUNTID AS ACCID,
        NV.EMAIL AS EMAIL,
        NV.USERNAME AS USERNAME,
        NV.FULLNAME AS FULLNAME,
        NV.POSITIONID AS POID,
        NV.CREATEDATE AS CREATEDATE,
        NV.DEPARTMENTID AS DEPARTMENTID,
        PB.DEPARTMENTNAME
	FROM `ACCOUNT` NV
	LEFT JOIN DEPARTMENT PB ON 
		(NV.DEPARTMENTID = PB.DEPARTMENTID))CV
WHERE CV.DEPARTMENTNAME ='MARKETING';

/*QUESTION 2*/
CREATE VIEW DETAIL_ACCOUNT_JOIN_GROUP_MAX AS
SELECT 		AC.ACCOUNTID, 
			AC.EMAIL, 
            AC.USERNAME, 
            AC.FULLNAME, 
            AC.POSITIONID, 
            AC.CREATEDATE, 
            COUNT(AC.ACCOUNTID) AS 'SO LUONG GROUP THAM GIA'
FROM		`ACCOUNT` AC 
INNER JOIN 	GROUPACCOUNT GA ON AC.ACCOUNTID = GA.ACCOUNTID
GROUP BY	AC.ACCOUNTID
HAVING		COUNT(AC.ACCOUNTID) = (SELECT MAX(COUNTA)
								   FROM(
										SELECT COUNT(AC.ACCOUNTID) AS COUNTA
										FROM GROUPACCOUNT GA 
										INNER JOIN `ACCOUNT` AC ON 
											GA.ACCOUNTID = AC.ACCOUNTID
										GROUP BY AC.ACCOUNTID) AS MAXCONTENT);


/*QUESTION 3*/
CREATE VIEW VIEW_INVALID_CONTENT AS
SELECT*
FROM QUESTION 
WHERE LENGTH(CONTENT) > 300;
DELETE FROM VIEW_INVALID_CONTENT
 WHERE LENGTH(CONTENT) > 300;

/*QUESTION 4*/
CREATE VIEW LIST_DEPARTMENT_WITH_THE_MOST_EMPLOYEES AS
SELECT 		PB.DEPARTMENTID, 
			PB.DEPARTMENTNAME, 
            COUNT(AC.ACCOUNTID) AS 'SO LUONG NHAN VIEN'
FROM		`DEPARTMENT` PB
INNER JOIN 	`ACCOUNT` AC ON AC.DEPARTMENTID = PB.DEPARTMENTID
GROUP BY	AC.DEPARTMENTID
HAVING		COUNT(AC.DEPARTMENTID) = (SELECT MAX(COUNTD)
									  FROM(
										SELECT COUNT(AC.DEPARTMENTID) AS COUNTD
										FROM DEPARTMENT PB 
										INNER JOIN `ACCOUNT` AC ON 
											PB.DEPARTMENTID = AC.DEPARTMENTID
										GROUP BY AC.DEPARTMENTID) AS MAXCONTENT);
/*QUESTION 5*/
CREATE VIEW LIST_QUESTION_OF_NGUYEN AS
SELECT
	Q.QUESTIONID, 
    Q.CONTENT, 
    Q.CATEGORYID, 
    Q.TYPEID, 
    Q.CREATORID, 
    Q.CREATEDATE, 
    NGUYEN.FULLNAME, 
    NGUYEN.DEPARTMENTID, 
    NGUYEN.POSITIONID
FROM QUESTION Q
INNER JOIN(SELECT *
		   FROM `ACCOUNT`
		   WHERE FULLNAME LIKE 'NGUYỄN%') NGUYEN ON 
				Q.CREATORID = NGUYEN.ACCOUNTID;